name: First workflow #siempre poner primero el nombre del workflow poniendo name:
on: workflow_dispatch #despues definimos on para cuando se va a disparar ese workflor, workflow_dispach hace referencia a cuando se dispara manualmente, es decir que espera a un usuario para que lo ejecute manualmente
#Una vez tenemos el nombre, y cuando será ejectuado, ponemos ahora si el trabajo que se va a hacer/ejectuar sí o sí tiene que ser JOBS (con S)
jobs: 
  first-job: #Es como una funcion, y se tiene que presionar TAB, y todo lo que este dentro de dicho trabajo se va a ejecutar, tambien se le tiene que poner un nombre, cualquier nombre
    #Lo que entre debajo de first-job, pertenece a dicha tarea
    runs-on: ubuntu-latest #Despues, definimos el runner que hara que corra en un ambiente en especifico, el cual tiene la palabra reservada runs on
    steps: #Una vez definimos el ambiente donde se ejecutara, ahora si corremos los steps
      - name: Print greeting #Para agregar los steps, agregamos un guion por cada step, y tambien por cada step, agregamos un nombre.
        run: echo "Hello_world" #aqeui ponemos el comando, que es ejecutado en la linea de comandos
      - name: Print bye bye
        run: echo "bye bye" 
  conditional: 
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: condicion
        run: echo "si funciona"
